openapi: 3.0.3
info:
  title: Todo App Authentication API
  version: 1.0.0
  description: REST API for user authentication (signup, signin, signout)

servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/auth/signup:
    post:
      summary: Register a new user
      description: Creates a new user account with email and password
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/signin:
    post:
      summary: Authenticate user
      description: Signs in a user with email and password, returns session
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninRequest'
      responses:
        '200':
          description: Signin successful
          description: Set-Cookie header with session token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SigninResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/signout:
    post:
      summary: Sign out user
      description: Ends the user's session
      tags:
        - Authentication
      responses:
        '200':
          description: Signout successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignoutResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/me:
    get:
      summary: Get current user
      description: Returns the currently authenticated user's information
      tags:
        - Authentication
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    SignupRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
          description: User's email address
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 128
          example: "securePassword123"
          description: User's password (8-128 characters)

    SigninRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
        password:
          type: string
          format: password
          example: "securePassword123"

    SigninResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserResponse'
        message:
          type: string
          example: "Signin successful"

    SignoutResponse:
      type: object
      properties:
        message:
          type: string
          example: "Signout successful"

    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        email:
          type: string
          format: email
          example: "user@example.com"
        created_at:
          type: string
          format: date-time
          example: "2025-12-31T10:00:00Z"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Validation failed"
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: "email"
              message:
                type: string
                example: "Invalid email format"

  securitySchemes:
    sessionCookie:
      type: apiKey
      in: cookie
      name: session
